//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCOC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleCategory
    {
        public long ScheduleTypeId { get; set; }
        public string ScheduleType { get; set; }
        public Nullable<bool> ISdeleted { get; set; }
    }
}
