//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCOC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Subjects
    {
        public long SubjectId { get; set; }
        public string SubjectName { get; set; }
        public Nullable<long> SubjectUserId { get; set; }
        public Nullable<System.DateTime> SubjectCreatedDate { get; set; }
        public Nullable<long> SubjectCreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
