//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCOC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OtherNotification
    {
        public long OtherNotificationId { get; set; }
        public string DisplayText { get; set; }
        public Nullable<long> NotificationReceivedUserId { get; set; }
        public string FormName { get; set; }
        public Nullable<bool> IsReaded { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> NotificationReceivedDate { get; set; }
    }
}
