//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCOC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MessageNotification
    {
        public long MessageNotificationId { get; set; }
        public Nullable<long> MessageReceivedUserId { get; set; }
        public Nullable<long> MessageSubjectId { get; set; }
        public string MessageText { get; set; }
        public Nullable<bool> IsReaded { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> MessageReceivedDate { get; set; }
        public Nullable<long> MessageSendUserId { get; set; }
    }
}
