//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCOC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MinistryInterests
    {
        public long MinistryId { get; set; }
        public string MinistryTitle { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
