//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCOC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ministry_Assigned_Users
    {
        public long Assign_MinistryId { get; set; }
        public Nullable<long> FK_User_ID { get; set; }
        public Nullable<long> FK_MinistryId { get; set; }
    }
}
