//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCOC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Setting
    {
        public long SettingId { get; set; }
        public string ChurchAddress { get; set; }
        public string SocialConnect_FacebookLink { get; set; }
        public string SocialConnect_TwitterLink { get; set; }
        public string Livestream_FacebookLink { get; set; }
        public string Livestream_YoutubeLink { get; set; }
    }
}
